### ISSUE TITLE
Choice providers for symfony forms

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#31]
What if there was a reusable form choice providers that could be use both by core and modules?
Often we need to reuse same choices in different forms, maybe to would be useful to have `PrestaShopBundle\Form\ChoiceProvider` namespace where all reusable choices could live?

Example choices provider for language. 

```php
final class LanguageChoicesProvider implements ChoiceValueProviderInterface {
    public function __construct(/** some dependencies needed to get language choices */) {
        //...
    }

    public function getChoices(): array {
        // logic to build choices array
    }
}
```
How it would look in yaml form_type definition. We only pass arrays to form type instance.

```yaml
    # multiple choices are need in this form type
    form.type.localization_configuration:
        class: 'PrestaShopBundle\Form\Admin\Improve\International\Localization\LocalizationConfigurationType'
        arguments:
            - '@prestashop.adapter.legacy.context'
            - '@=service("prestashop.bundle.form.language_choice_provider").getChoices()'
            - '@=service("prestashop.bundle.form.country_choice_provider").getChoices()'
            - '@=service("prestashop.bundle.form.currency_choice_provider").getChoices()'
            - '@=service("prestashop.bundle.form.timezone_choice_provider").getChoices()'
        tags:
            - { name: form.type }

    # only language choices are need in this form type
    form.type.example:
        class: 'PrestaShopBundle\Form\Admin\ExampleType'
        arguments:
            - '@=service("prestashop.bundle.form.language_choice_provider").getChoices()'
        tags:
            - { name: form.type }
```
