### ISSUE TITLE
Common options controller

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#70]
### Problem

When looking at how option forms are processed in controllers, you can see a pattern so called copy-paste.
What if we had common action for handling options processing?

### Example solution

This is how it could look like:

_NOTE: i did not test it yet and i dont know if that would actually work_

```php
class OptionsController extends AdminController
{
    public function processFormAction(Request $request, $formHandlerServiceId, $redirectRoute)
    {
        $this->dispatchHook(
            'action'.$request->attributes->get('_legacy_controller').'ControllerPostProcessBefore',
            ['controller' => $this]
        );

        $optionsFormHandler = $this->get($formHandlerServiceId);

        $optionsForm = $optionsFormHandler ->getForm();
        $optionsForm->handleRequest($request);

        if ($optionsForm->isSubmitted()) {
            $errors = $optionsFormHandler ->save($optionsForm->getData());

            if (empty($errors)) {
                $this->addFlash('success', $this->trans('Update successful', 'Admin.Notifications.Success'));

                return $this->redirectToRoute($redirectRoute);
            }

            $this->flashErrors($errors);
        }

        return $this->redirectToRoute($redirectRoute);
    }
}
```

And routes config:

```yaml
admin_geolocation_process_form:
    path: /process_form
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common\OptionsController
        _legacy_controller: AdminGeolocation # needed for access control & hook
        formHandlerServiceId: geolocation.options.form.handler # configures form handler service id
        redirectRoute: admin_geolocation # redirect route after form is processed

admin_localization_process_form:
    path: /
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common\OptionsController
        _legacy_controller: AdminLocalization
        formHandlerServiceId: localization.options.form.handler
        redirectRoute: admin_localization

# and so on for every options form processing
# ...
```

This could be even improved with argument resolving to resolve FormHandler parameter in action: `processFormAction(Request $request, FormHandlerInterface $formHandler, $redirectRoute)`

### Outcome

Pros: 
- prevent code duplication
- hooks can be dispatched before and/or after options form process (at the moment some controllers dispatch hook when processing options and some doesnt)
- less code to maintain

Cons:
- ??? 🤔
